scrum/config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

# Copyright © Emilio González Montaña
# Licence: Attribution & no derivatives
#   * Attribution to the plugin web page URL should be done if you want to use it.
#     https://redmine.ociotec.com/projects/redmine-plugin-scrum
#   * No derivatives of this plugin (or partial) are allowed.
# Take a look to licence.txt file at plugin root folder for further details.

resources :projects do
  resources :sprints, :shallow => true do
    member do
      get :edit_effort
      post :update_effort
      get :burndown
      get :burndown_graph
      get :stats
      post :sort
    end
    collection do
      get :burndown_index
      get :stats_index
    end
  end
  post "sprints/change_issue_status",
       :controller => :sprints, :action => :change_issue_status,
       :as => :sprints_change_issue_status

  resources :product_backlog, :shallow => true do
    member do
      post :sort
      post :create_pbi
      get :burndown
      get :burndown_graph
      get :check_dependencies
      get :release_plan
    end
  end
  get "product_backlog/new_pbi/:tracker_id",
      :controller => :product_backlog, :action => :new_pbi,
      :as => :product_backlog_new_pbi

  get "scrum/stats",
      :controller => :scrum, :action => :stats,
      :as => :scrum_stats

end

post "issues/:id/story_points",
     :controller => :scrum, :action => :change_story_points,
     :as => :change_story_points
post "issues/:id/remaining_story_points",
     :controller => :scrum, :action => :change_remaining_story_points,
     :as => :change_remaining_story_points
post "issues/:id/pending_effort",
     :controller => :scrum, :action => :change_pending_effort,
     :as => :change_pending_effort
post "issues/:id/pending_efforts",
     :controller => :scrum, :action => :change_pending_efforts,
     :as => :change_pending_efforts
post "issues/:id/assigned_to",
     :controller => :scrum, :action => :change_assigned_to,
     :as => :change_assigned_to
get "issues/:id/time_entry",
     :controller => :scrum, :action => :new_time_entry,
     :as => :new_scrum_time_entry
post "issues/:id/time_entry",
     :controller => :scrum, :action => :create_time_entry,
     :as => :create_scrum_time_entry
get "scrum/:sprint_id/new_pbi/:tracker_id",
     :controller => :scrum, :action => :new_pbi,
     :as => :new_pbi
post "scrum/:sprint_id/create_pbi",
     :controller => :scrum, :action => :create_pbi,
     :as => :create_pbi
get "scrum/:pbi_id/new/:tracker_id",
    :controller => :scrum, :action => :new_task,
    :as => :new_task
post "scrum/:pbi_id/create_task",
     :controller => :scrum, :action => :create_task,
     :as => :create_task
get "scrum/:pbi_id/edit_pbi",
    :controller => :scrum, :action => :edit_pbi,
    :as => :edit_pbi
post "scrum/:pbi_id/update_pbi",
     :controller => :scrum, :action => :update_pbi,
     :as => :update_pbi
get "scrum/:pbi_id/move/:position",
    :controller => :scrum, :action => :move_pbi,
    :as => :move_pbi
get "scrum/:id/edit_task",
    :controller => :scrum, :action => :edit_task,
    :as => :edit_task
post "scrum/:id/update_task",
     :controller => :scrum, :action => :update_task,
     :as => :update_task
post "scrum/:pbi_id/move_to_last_sprint",
     :controller => :scrum, :action => :move_to_last_sprint,
     :as => :move_to_last_sprint
post "scrum/:sprint_id/move_not_closed_pbis_to_last_sprint",
     :controller => :scrum, :action => :move_not_closed_pbis_to_last_sprint,
     :as => :move_not_closed_pbis_to_last_sprint
post "scrum/:pbi_id/move_to_product_backlog",
     :controller => :scrum, :action => :move_to_product_backlog,
     :as => :move_to_product_backlog

scrum/app/views/scrum_hooks/issues/_bulk_edit.html.erb
<%- if defined?(@project) and @project.scrum? -%>
  <% if @safe_attributes.include?("sprint_id") -%>
    <p>
      <label for="sprint_id"><%= l(:field_sprint) %></label>
      <%- sprints = @project.all_open_sprints_and_product_backlogs
          options = content_tag("option", l(:label_no_change_option), :value => "") +
                    options_from_collection_for_select(sprints, :id, :name) -%>
      <%= select_tag "issue[sprint_id]", options %>
    </p>
  <%- end -%>
  <%- if User.current.allowed_to?(:edit_pending_effort, @project) -%>
    <p>
      <label for="pending_effort"><%= l(:field_pending_effort) %></label>
      <%= text_field_tag "issue[pending_effort]", "", :size => 3 %>
    </p>
  <%- end -%>
<%- end -%>

scrum/app/views/scrum_hooks/issues/_edit_pending_effort.html.erb
<%- if User.current.allowed_to?(:edit_pending_effort, @issue.project) -%>
  <div id="edit_pending_effort" class="scrum-dialog"
       title="<%= l(@issue.is_task? ? :field_pending_effort : :label_remaining_story_point_plural) %>">
    <%= form_tag(change_pending_efforts_path(issue), :method => :post) do %>
      <table align="center">
        <tr>
          <th><%= l(:field_effective_date) %></th>
          <th><%= l(@issue.is_task? ? :field_hours : :label_remaining_story_point_plural) %></th>
        </tr>
        <%- issue.pending_efforts.each_with_index do |pending_effort, index| -%>
          <tr>
            <th>
              <%= format_date(pending_effort.date) %>
            </th>
            <td>
              <%= text_field_tag "pending_efforts[#{pending_effort.id}]",
                                 pending_effort.effort,
                                 :size => 2 %>
            </td>
          </tr>
        <%- end -%>
        <tr>
          <td colspan="2" align="left">
            <%= submit_tag l(:button_edit), :name => 'edit', :disable_with => l(:label_loading) %>
          </td>
        </tr>
      </table>
    <% end %>
  </div>
<%- end -%>

scrum/app/views/scrum_hooks/issues/_form.html.erb
<%- assignable_sprints = @issue.assignable_sprints -%>
<%- if assignable_sprints.any? -%>
  <div class="splitcontent">
    <div class="splitcontentleft">
      <p>
        <%- selected = @issue.sprint ? @issue.sprint.id.to_s : nil -%>
        <%= form.select :sprint_id,
                        options_from_collection_for_select(assignable_sprints, 'id', 'name', selected),
                        :include_blank => true %>
      </p>
    </div>
    <%- if (@issue.is_task? or @issue.is_pbi?) and @issue.scrum? and
        User.current.allowed_to?(:edit_pending_effort, @issue.project)-%>
      <div class="splitcontentright">
        <p>
          <%= form.text_field :pending_effort, :size => 3,
                              :label => @issue.is_pbi? ? l(:label_remaining_story_point_plural) : nil %>
        </p>
      </div>
    <%- end -%>
  </div>
<%- end -%>

scrum/app/views/scrum_hooks/issues/_pending_effort.html.erb
<%- if User.current.allowed_to?(:view_pending_effort, @issue.project) -%>
  <div id="pending_effort" class="scrum-dialog"
       title="<%= l(@issue.is_task? ? :field_pending_effort : :label_remaining_story_point_plural) %>">
    <table align="center">
      <tr>
        <th><%= l(:field_effective_date) %></th>
        <th><%= l(@issue.is_task? ? :field_hours : :label_remaining_story_point_plural) %></th>
      </tr>
      <%- issue.pending_efforts.each do |pending_effort| -%>
        <tr>
          <td align="center"><%= format_date(pending_effort.date) %></td>
          <td align="center"><%= pending_effort.effort %></td>
        </tr>
      <%- end -%>
    </table>
  </div>
<%- end -%>

scrum/app/views/scrum_hooks/issues/_show.html.erb
<%- if @issue.scrum? -%>
  <%= issue_fields_rows do |rows|
    if @issue.sprint.nil?
      content = ''
    else
      if @issue.sprint.is_product_backlog
        object = project_product_backlog_index_path(@issue.sprint.project)
      else
        object = @issue.sprint
      end
      content = link_to(h(@issue.sprint.name), object)
    end
    rows.left l(:label_sprint), raw(content), :class => 'sprint'

    if @issue.is_pbi?
      content = ''
      if @issue.has_remaining_story_points?
        if User.current.allowed_to?(:view_pending_effort, @issue.project)
          content = render_sps(@issue.remaining_story_points) +
                    raw('&nbsp;') +
                    link_to('', '#', :class => 'icon icon-zoom-in',
                            :onclick => '$("#pending_effort").dialog({modal: true});') +
                    render(:partial => 'scrum_hooks/issues/pending_effort', :locals => {:issue => @issue})
        end
        if User.current.allowed_to?(:edit_pending_effort, @issue.project)
          content += link_to('', '#', :class => 'icon icon-edit',
                             :onclick => '$("#edit_pending_effort").dialog({modal: true});') +
                     render(:partial => 'scrum_hooks/issues/edit_pending_effort', :locals => {:issue => @issue})
        end
      end
      if Scrum::Setting.use_remaining_story_points? and
         User.current.allowed_to?(:view_pending_effort, @issue.project) or
         User.current.allowed_to?(:edit_pending_effort, @issue.project)
        rows.right l(:label_remaining_story_point_plural), raw(content), :class => 'pending_effort'
      end
    elsif @issue.is_task?
      content = ''
      if @issue.has_pending_effort?
        if User.current.allowed_to?(:view_pending_effort, @issue.project)
          content = raw(@issue.pending_effort ? l('datetime.distance_in_words.x_hours', :count => @issue.pending_effort) : '') +
                    raw('&nbsp;') +
                    link_to('', '#', :class => 'icon icon-zoom-in',
                            :onclick => '$("#pending_effort").dialog({modal: true});') +
                    render(:partial => 'scrum_hooks/issues/pending_effort', :locals => {:issue => @issue})
        end
        if User.current.allowed_to?(:edit_pending_effort, @issue.project)
          content += link_to('', '#', :class => 'icon icon-edit',
                             :onclick => '$("#edit_pending_effort").dialog({modal: true});') +
                     render(:partial => 'scrum_hooks/issues/edit_pending_effort', :locals => {:issue => @issue})
        end
      end
      if User.current.allowed_to?(:view_pending_effort, @issue.project) or
         User.current.allowed_to?(:edit_pending_effort, @issue.project)
        rows.right l(:field_pending_effort), raw(content), :class => 'pending_effort'
      end
    end
  end %>
<%- end -%>